### ISSUE TITLE
testProperty deprecated in tasty-hedgehog ^>=1.2.0.0

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [haskell-works/tasty-discover#20]
As of `tasty-hedgehog-1.2.0.0`, `testProperty` is deprecated with message "Deprecated: testProperty will cause Hedgehog to provide incorrect instructions for re-checking properties".

`testPropertyNamed :: TestName -> PropertyName -> Property -> TestTree` is the recommended name. It would be great if `tasty-discover` generated calls to this function if available.

If you can offer up some pointers, I may be able to have a crack at a PR.

**Comment by newhoggy** [comment]
I don't recall what happen exactly, but I believe this is resolved now.
