### ISSUE TITLE
Make `TestGroup` typeclass public

### ISSUE THREAD

**Issue by Martoon-00** [haskell-works/tasty-discover#3]
We have a use case when it would be convenient to add our own test suite types so that we are able to define

```haskell
test_MyTest :: MyTestSuite
test_MyTest = ...
```

and in theory, this is supported via `TestGroup` typeclass. However, its definition is currently part of the code generated by the plugin.

It would be very nice if `TestGroup` typeclass is made part of the library, so that users could define their own instances for it and later avoid manual conversions between `MyTestSuite` and `TestTree`.

**Comment by newhoggy** [comment]
Isn't `TestGroup` defined in `tasty` rather than `tasty-discover`?

**Comment by Martoon-00** [comment]
I can't find it in `tasty`, AFAIU it is defined [here](https://github.com/haskell-works/tasty-discover/blob/6f994d5d8a6eaea6e858b2a0a2cc6ee0c943c553/library/Test/Tasty/Generator.hs#L143) in this repository.

**Comment by newhoggy** [comment]
Hmm, I think I can't export `TestGroup` because `tasty-discover` is not meant to be used as a library.  It needs to be added to `tasty` if you want it.

**Comment by Martoon-00** [comment]
I was just going to write an argumentation why this may still be worth trying, and then noticed the commit adding this functionality 5 days after your last comment :sweat_smile: 

I tried it, and it works well for me, thanks! 

Somehow, I don't even need to depend on `tasty-discovery` as a library in the code that _uses_ my custom `Tasty` instance (in the test suite), only in the code that defines this instance. For me that sounds like a very minor and natural cost for ability to, in some sort, extend `tasty-discovery`.

I'll try to post here once I try this functionality in our real project, so that there is a use case for the reference.
