### ISSUE TITLE
Please, instruct in the docs that executable should be installed in the PATH

### ISSUE THREAD

**Issue by Anton-Latukha** [haskell-works/tasty-discover#4]
I encountered a:
```
ghc: could not execute: tasty-discover
```
build reports.

`tasty-discover` is in the `*.cabal` dependencies.
`tasty-discover` gets downloaded and build by Cabal during project build.

But it was throwing `ghc: could not execute: tasty-discover` error, websearch pointed-out there is a number of reports to different projects of this, and all what I read about it - is that it is a "project internal issue".

Because I do not have prior experience with `tasty-discover` I looked at the docs - and they indicated to me that nothing is wrong, that there is no need to install anything.

Only when a fellow member of a team suggested that `tasty-discover` should be installed before the build with something like `cabal v2-install tasty-discover` - only by help and trial and error that it needs installation was discovered.

This was encountered while doing CI/tests for the project where I first encountered `tasty-discover` test suite (https://github.com/haskell-nix/hnix-store/pull/88).

Please, add information that people need to install the executable, where it would be appropriate to instruct.

---

It was pointed-out to me that such cases are solved by:
```
  build-tool-depends:
    tasty-discover:tasty-discover
```
That is how it works properly.
So, please, add this to the documentation.

**Comment by georgefst** [comment]
Yeah, I just hit this as well. The tl;dr is that the docs should definitely mention `build-tool-depends` - which is preferable to installing globally as cabal will manage the version properly.

**Comment by Anton-Latukha** [comment]
Yes, as was written
```
  build-tool-depends:
    tasty-discover:tasty-discover
```

That would also allow for `.cabal` description to be converted into Nix language properly. To find a proper solution I arrived up to the main Nixpkgs Haskell maintainer giving me the proper answer, while that just should be in docs.

**Comment by newhoggy** [comment]
Thanks for the suggestion.

**Comment by Anton-Latukha** [comment]
@newhoggy

Thank you from the community.

I was rambling here a little, that is the way I am.

Thank you again, now setup flow for people would be smooth.
